/* File: num_types.f90module.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Oct 30 21:28:07 2013
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *num_types.f90_error;
static PyObject *num_types.f90_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = num_types.f90_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = num_types.f90_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** equal_rank1 ********************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1[] = "\
Function signature:\n\
  equal_rank1 = equal_rank1(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-1 array('f') with bounds (f2py_a_d0)\n"
"  b : input rank-1 array('f') with bounds (f2py_b_d0)\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank1 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank1 = 0;
  float *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  float *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_b_d0 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank1",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank1 to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_FLOAT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `b' of num_types.f90.numerical_utilities.equal_rank1 to C/Fortran array" );
  } else {
    b = (float *)(capi_b_tmp->data);

  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank1() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_rank1 */
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_b_d0 */
  f2py_b_d0 = shape(b, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank1,a,b,&tolerance,&f2py_a_d0,&f2py_b_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank1);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_b_d0 */
  /* End of cleaning variable f2py_a_d0 */
  /* End of cleaning variable equal_rank1 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of equal_rank1 *****************************/

/******************************** equal_rank2 ********************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2[] = "\
Function signature:\n\
  equal_rank2 = equal_rank2(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-2 array('f') with bounds (f2py_a_d0,f2py_a_d1)\n"
"  b : input rank-2 array('f') with bounds (f2py_b_d0,f2py_b_d1)\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank2 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank2 = 0;
  float *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  float *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_a_d1 = 0;
  int f2py_b_d0 = 0;
  int f2py_b_d1 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank2",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank2 to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_FLOAT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `b' of num_types.f90.numerical_utilities.equal_rank2 to C/Fortran array" );
  } else {
    b = (float *)(capi_b_tmp->data);

  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank2() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_rank2 */
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_a_d1 */
  f2py_a_d1 = shape(a, 1);
  /* Processing variable f2py_b_d0 */
  f2py_b_d0 = shape(b, 0);
  /* Processing variable f2py_b_d1 */
  f2py_b_d1 = shape(b, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank2,a,b,&tolerance,&f2py_a_d0,&f2py_a_d1,&f2py_b_d0,&f2py_b_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_b_d1 */
  /* End of cleaning variable f2py_b_d0 */
  /* End of cleaning variable f2py_a_d1 */
  /* End of cleaning variable f2py_a_d0 */
  /* End of cleaning variable equal_rank2 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of equal_rank2 *****************************/

/******************************** equal_rank3 ********************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank3[] = "\
Function signature:\n\
  equal_rank3 = equal_rank3(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-3 array('f') with bounds (f2py_a_d0,f2py_a_d1,f2py_a_d2)\n"
"  b : input rank-3 array('f') with bounds (f2py_b_d0,f2py_b_d1,f2py_b_d2)\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank3 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank3 = 0;
  float *a = NULL;
  npy_intp a_Dims[3] = {-1, -1, -1};
  const int a_Rank = 3;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  float *b = NULL;
  npy_intp b_Dims[3] = {-1, -1, -1};
  const int b_Rank = 3;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_a_d1 = 0;
  int f2py_a_d2 = 0;
  int f2py_b_d0 = 0;
  int f2py_b_d1 = 0;
  int f2py_b_d2 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank3",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank3 to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_FLOAT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `b' of num_types.f90.numerical_utilities.equal_rank3 to C/Fortran array" );
  } else {
    b = (float *)(capi_b_tmp->data);

  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank3() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_rank3 */
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_a_d1 */
  f2py_a_d1 = shape(a, 1);
  /* Processing variable f2py_a_d2 */
  f2py_a_d2 = shape(a, 2);
  /* Processing variable f2py_b_d0 */
  f2py_b_d0 = shape(b, 0);
  /* Processing variable f2py_b_d1 */
  f2py_b_d1 = shape(b, 1);
  /* Processing variable f2py_b_d2 */
  f2py_b_d2 = shape(b, 2);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank3,a,b,&tolerance,&f2py_a_d0,&f2py_a_d1,&f2py_a_d2,&f2py_b_d0,&f2py_b_d1,&f2py_b_d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank3);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_b_d2 */
  /* End of cleaning variable f2py_b_d1 */
  /* End of cleaning variable f2py_b_d0 */
  /* End of cleaning variable f2py_a_d2 */
  /* End of cleaning variable f2py_a_d1 */
  /* End of cleaning variable f2py_a_d0 */
  /* End of cleaning variable equal_rank3 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of equal_rank3 *****************************/

/******************************** equal_scalar ********************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar[] = "\
Function signature:\n\
  equal_scalar = equal_scalar(a,b,tolerance)\n\
Required arguments:\n"
"  a : input float\n"
"  b : input float\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_scalar : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_scalar(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_scalar = 0;
  float a = 0;
  PyObject *a_capi = Py_None;
  float b = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_scalar",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
    f2py_success = float_from_pyobj(&a,a_capi,"num_types.f90.numerical_utilities.equal_scalar() 1st argument (a) can't be converted to float");
  if (f2py_success) {
  /* Processing variable b */
    f2py_success = float_from_pyobj(&b,b_capi,"num_types.f90.numerical_utilities.equal_scalar() 2nd argument (b) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_scalar */
  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_scalar() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_scalar,&a,&b,&tolerance);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_scalar);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  /* End of cleaning variable equal_scalar */
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  } /*if (f2py_success) of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of equal_scalar ****************************/

/*************************** equal_scalar_real_int ***************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar_real_int[] = "\
Function signature:\n\
  equal_scalar_real_int = equal_scalar_real_int(a,b,tolerance)\n\
Required arguments:\n"
"  a : input float\n"
"  b : input int\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_scalar_real_int : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_scalar_real_int(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_scalar_real_int = 0;
  float a = 0;
  PyObject *a_capi = Py_None;
  int b = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_scalar_real_int",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
    f2py_success = float_from_pyobj(&a,a_capi,"num_types.f90.numerical_utilities.equal_scalar_real_int() 1st argument (a) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_scalar_real_int */
  /* Processing variable b */
    f2py_success = int_from_pyobj(&b,b_capi,"num_types.f90.numerical_utilities.equal_scalar_real_int() 2nd argument (b) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_scalar_real_int() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_scalar_real_int,&a,&b,&tolerance);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_scalar_real_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  /* End of cleaning variable equal_scalar_real_int */
  } /*if (f2py_success) of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of equal_scalar_real_int ************************/

/**************************** equal_scalar_int_int ****************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar_int_int[] = "\
Function signature:\n\
  equal_scalar_int_int = equal_scalar_int_int(a,b,tolerance)\n\
Required arguments:\n"
"  a : input int\n"
"  b : input int\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_scalar_int_int : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_scalar_int_int(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_scalar_int_int = 0;
  int a = 0;
  PyObject *a_capi = Py_None;
  int b = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_scalar_int_int",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
    f2py_success = int_from_pyobj(&a,a_capi,"num_types.f90.numerical_utilities.equal_scalar_int_int() 1st argument (a) can't be converted to int");
  if (f2py_success) {
  /* Processing variable b */
    f2py_success = int_from_pyobj(&b,b_capi,"num_types.f90.numerical_utilities.equal_scalar_int_int() 2nd argument (b) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_scalar_int_int() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_scalar_int_int */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_scalar_int_int,&a,&b,&tolerance);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_scalar_int_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable equal_scalar_int_int */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  } /*if (f2py_success) of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of equal_scalar_int_int ************************/

/***************************** equal_rank1_rank0 *****************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1_rank0[] = "\
Function signature:\n\
  equal_rank1_rank0 = equal_rank1_rank0(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-1 array('f') with bounds (f2py_a_d0)\n"
"  b : input float\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank1_rank0 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank1_rank0(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank1_rank0 = 0;
  float *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  float b = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank1_rank0",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank1_rank0 to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable equal_rank1_rank0 */
  /* Processing variable b */
    f2py_success = float_from_pyobj(&b,b_capi,"num_types.f90.numerical_utilities.equal_rank1_rank0() 2nd argument (b) can't be converted to float");
  if (f2py_success) {
  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank1_rank0() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank1_rank0,a,&b,&tolerance,&f2py_a_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank1_rank0);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_a_d0 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  /* End of cleaning variable equal_rank1_rank0 */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of equal_rank1_rank0 **************************/

/***************************** equal_rank2_rank0 *****************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2_rank0[] = "\
Function signature:\n\
  equal_rank2_rank0 = equal_rank2_rank0(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-2 array('f') with bounds (f2py_a_d0,f2py_a_d1)\n"
"  b : input float\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank2_rank0 : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank2_rank0(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank2_rank0 = 0;
  float *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  float b = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_a_d1 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank2_rank0",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank2_rank0 to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable b */
    f2py_success = float_from_pyobj(&b,b_capi,"num_types.f90.numerical_utilities.equal_rank2_rank0() 2nd argument (b) can't be converted to float");
  if (f2py_success) {
  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank2_rank0() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable equal_rank2_rank0 */
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_a_d1 */
  f2py_a_d1 = shape(a, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank2_rank0,a,&b,&tolerance,&f2py_a_d0,&f2py_a_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank2_rank0);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_a_d1 */
  /* End of cleaning variable f2py_a_d0 */
  /* End of cleaning variable equal_rank2_rank0 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  } /*if (f2py_success) of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of equal_rank2_rank0 **************************/

/**************************** equal_rank2_real_int ****************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2_real_int[] = "\
Function signature:\n\
  equal_rank2_real_int = equal_rank2_real_int(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-2 array('f') with bounds (f2py_a_d0,f2py_a_d1)\n"
"  b : input rank-2 array('i') with bounds (f2py_b_d0,f2py_b_d1)\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank2_real_int : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank2_real_int(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,int*,float*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank2_real_int = 0;
  float *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_a_d1 = 0;
  int f2py_b_d0 = 0;
  int f2py_b_d1 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank2_real_int",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank2_real_int to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable equal_rank2_real_int */
  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_INT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `b' of num_types.f90.numerical_utilities.equal_rank2_real_int to C/Fortran array" );
  } else {
    b = (int *)(capi_b_tmp->data);

  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank2_real_int() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_a_d1 */
  f2py_a_d1 = shape(a, 1);
  /* Processing variable f2py_b_d0 */
  f2py_b_d0 = shape(b, 0);
  /* Processing variable f2py_b_d1 */
  f2py_b_d1 = shape(b, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank2_real_int,a,b,&tolerance,&f2py_a_d0,&f2py_a_d1,&f2py_b_d0,&f2py_b_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank2_real_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_b_d1 */
  /* End of cleaning variable f2py_b_d0 */
  /* End of cleaning variable f2py_a_d1 */
  /* End of cleaning variable f2py_a_d0 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  /* End of cleaning variable equal_rank2_real_int */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of equal_rank2_real_int ************************/

/**************************** equal_rank1_real_int ****************************/
static char doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1_real_int[] = "\
Function signature:\n\
  equal_rank1_real_int = equal_rank1_real_int(a,b,tolerance)\n\
Required arguments:\n"
"  a : input rank-1 array('f') with bounds (f2py_a_d0)\n"
"  b : input rank-1 array('i') with bounds (f2py_b_d0)\n"
"  tolerance : input float\n"
"Return objects:\n"
"  equal_rank1_real_int : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_numerical_utilities_equal_rank1_real_int(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,int*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int equal_rank1_real_int = 0;
  float *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  float tolerance = 0;
  PyObject *tolerance_capi = Py_None;
  int f2py_a_d0 = 0;
  int f2py_b_d0 = 0;
  static char *capi_kwlist[] = {"a","b","tolerance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:num_types.f90.numerical_utilities.equal_rank1_real_int",\
    capi_kwlist,&a_capi,&b_capi,&tolerance_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `a' of num_types.f90.numerical_utilities.equal_rank1_real_int to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable equal_rank1_real_int */
  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_INT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `b' of num_types.f90.numerical_utilities.equal_rank1_real_int to C/Fortran array" );
  } else {
    b = (int *)(capi_b_tmp->data);

  /* Processing variable tolerance */
    f2py_success = float_from_pyobj(&tolerance,tolerance_capi,"num_types.f90.numerical_utilities.equal_rank1_real_int() 3rd argument (tolerance) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f2py_a_d0 */
  f2py_a_d0 = shape(a, 0);
  /* Processing variable f2py_b_d0 */
  f2py_b_d0 = shape(b, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&equal_rank1_real_int,a,b,&tolerance,&f2py_a_d0,&f2py_b_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",equal_rank1_real_int);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_b_d0 */
  /* End of cleaning variable f2py_a_d0 */
  } /*if (f2py_success) of tolerance*/
  /* End of cleaning variable tolerance */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  /* End of cleaning variable equal_rank1_real_int */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of equal_rank1_real_int ************************/

/************************* minkowski_conditions_check *************************/
static char doc_f2py_rout_num_types.f90_vector_matrix_utilities_minkowski_conditions_check[] = "\
Function signature:\n\
  minkowski_conditions_check = minkowski_conditions_check(basis,eps)\n\
Required arguments:\n"
"  basis : input rank-2 array('f') with bounds (3,3)\n"
"  eps : input float\n"
"Return objects:\n"
"  minkowski_conditions_check : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_num_types.f90_vector_matrix_utilities_minkowski_conditions_check(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int minkowski_conditions_check = 0;
  float *basis = NULL;
  npy_intp basis_Dims[2] = {-1, -1};
  const int basis_Rank = 2;
  PyArrayObject *capi_basis_tmp = NULL;
  int capi_basis_intent = 0;
  PyObject *basis_capi = Py_None;
  float eps = 0;
  PyObject *eps_capi = Py_None;
  static char *capi_kwlist[] = {"basis","eps",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:num_types.f90.vector_matrix_utilities.minkowski_conditions_check",\
    capi_kwlist,&basis_capi,&eps_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable minkowski_conditions_check */
  /* Processing variable basis */
  basis_Dims[0]=3,basis_Dims[1]=3;
  capi_basis_intent |= F2PY_INTENT_IN;
  capi_basis_tmp = array_from_pyobj(NPY_FLOAT,basis_Dims,basis_Rank,capi_basis_intent,basis_capi);
  if (capi_basis_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `basis' of num_types.f90.vector_matrix_utilities.minkowski_conditions_check to C/Fortran array" );
  } else {
    basis = (float *)(capi_basis_tmp->data);

  /* Processing variable eps */
    f2py_success = float_from_pyobj(&eps,eps_capi,"num_types.f90.vector_matrix_utilities.minkowski_conditions_check() 2nd argument (eps) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&minkowski_conditions_check,basis,&eps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",minkowski_conditions_check);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of eps*/
  /* End of cleaning variable eps */
  if((PyObject *)capi_basis_tmp!=basis_capi) {
    Py_XDECREF(capi_basis_tmp); }
  }  /*if (capi_basis_tmp == NULL) ... else of basis*/
  /* End of cleaning variable basis */
  /* End of cleaning variable minkowski_conditions_check */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************* end of minkowski_conditions_check *********************/

/****************************** reduce_C_in_ABC ******************************/
static char doc_f2py_rout_num_types.f90_vector_matrix_utilities_reduce_C_in_ABC[] = "\
Function signature:\n\
  reduce_C_in_ABC(A,B,C,eps)\n\
Required arguments:\n"
"  A : in/output rank-1 array('f') with bounds (3)\n"
"  B : in/output rank-1 array('f') with bounds (3)\n"
"  C : in/output rank-1 array('f') with bounds (3)\n"
"  eps : input float";
/*  */
static PyObject *f2py_rout_num_types.f90_vector_matrix_utilities_reduce_C_in_ABC(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *A = NULL;
  npy_intp A_Dims[1] = {-1};
  const int A_Rank = 1;
  PyArrayObject *capi_A_tmp = NULL;
  int capi_A_intent = 0;
  PyObject *A_capi = Py_None;
  float *B = NULL;
  npy_intp B_Dims[1] = {-1};
  const int B_Rank = 1;
  PyArrayObject *capi_B_tmp = NULL;
  int capi_B_intent = 0;
  PyObject *B_capi = Py_None;
  float *C = NULL;
  npy_intp C_Dims[1] = {-1};
  const int C_Rank = 1;
  PyArrayObject *capi_C_tmp = NULL;
  int capi_C_intent = 0;
  PyObject *C_capi = Py_None;
  float eps = 0;
  PyObject *eps_capi = Py_None;
  static char *capi_kwlist[] = {"A","B","C","eps",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:num_types.f90.vector_matrix_utilities.reduce_C_in_ABC",\
    capi_kwlist,&A_capi,&B_capi,&C_capi,&eps_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable A */
  A_Dims[0]=3;
  capi_A_intent |= F2PY_INTENT_INOUT;
  capi_A_tmp = array_from_pyobj(NPY_FLOAT,A_Dims,A_Rank,capi_A_intent,A_capi);
  if (capi_A_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 1st argument `A' of num_types.f90.vector_matrix_utilities.reduce_C_in_ABC to C/Fortran array" );
  } else {
    A = (float *)(capi_A_tmp->data);

  /* Processing variable C */
  C_Dims[0]=3;
  capi_C_intent |= F2PY_INTENT_INOUT;
  capi_C_tmp = array_from_pyobj(NPY_FLOAT,C_Dims,C_Rank,capi_C_intent,C_capi);
  if (capi_C_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 3rd argument `C' of num_types.f90.vector_matrix_utilities.reduce_C_in_ABC to C/Fortran array" );
  } else {
    C = (float *)(capi_C_tmp->data);

  /* Processing variable eps */
    f2py_success = float_from_pyobj(&eps,eps_capi,"num_types.f90.vector_matrix_utilities.reduce_C_in_ABC() 4th argument (eps) can't be converted to float");
  if (f2py_success) {
  /* Processing variable B */
  B_Dims[0]=3;
  capi_B_intent |= F2PY_INTENT_INOUT;
  capi_B_tmp = array_from_pyobj(NPY_FLOAT,B_Dims,B_Rank,capi_B_intent,B_capi);
  if (capi_B_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(num_types.f90_error,"failed in converting 2nd argument `B' of num_types.f90.vector_matrix_utilities.reduce_C_in_ABC to C/Fortran array" );
  } else {
    B = (float *)(capi_B_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(A,B,C,&eps);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_B_tmp!=B_capi) {
    Py_XDECREF(capi_B_tmp); }
  }  /*if (capi_B_tmp == NULL) ... else of B*/
  /* End of cleaning variable B */
  } /*if (f2py_success) of eps*/
  /* End of cleaning variable eps */
  if((PyObject *)capi_C_tmp!=C_capi) {
    Py_XDECREF(capi_C_tmp); }
  }  /*if (capi_C_tmp == NULL) ... else of C*/
  /* End of cleaning variable C */
  if((PyObject *)capi_A_tmp!=A_capi) {
    Py_XDECREF(capi_A_tmp); }
  }  /*if (capi_A_tmp == NULL) ... else of A*/
  /* End of cleaning variable A */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of reduce_C_in_ABC ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_numerical_utilities_def[] = {
  {"equal_rank1",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank1,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1},
  {"equal_rank2",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank2,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2},
  {"equal_rank3",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank3,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank3},
  {"equal_scalar",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_scalar,doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar},
  {"equal_scalar_real_int",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_scalar_real_int,doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar_real_int},
  {"equal_scalar_int_int",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_scalar_int_int,doc_f2py_rout_num_types.f90_numerical_utilities_equal_scalar_int_int},
  {"equal_rank1_rank0",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank1_rank0,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1_rank0},
  {"equal_rank2_rank0",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank2_rank0,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2_rank0},
  {"equal_rank2_real_int",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank2_real_int,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank2_real_int},
  {"equal_rank1_real_int",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_numerical_utilities_equal_rank1_real_int,doc_f2py_rout_num_types.f90_numerical_utilities_equal_rank1_real_int},
  {NULL}
};

static void f2py_setup_numerical_utilities(char *equal_rank1,char *equal_rank2,char *equal_rank3,char *equal_scalar,char *equal_scalar_real_int,char *equal_scalar_int_int,char *equal_rank1_rank0,char *equal_rank2_rank0,char *equal_rank2_real_int,char *equal_rank1_real_int) {
  int i_f2py=0;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank1;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank2;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank3;
  f2py_numerical_utilities_def[i_f2py++].data = equal_scalar;
  f2py_numerical_utilities_def[i_f2py++].data = equal_scalar_real_int;
  f2py_numerical_utilities_def[i_f2py++].data = equal_scalar_int_int;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank1_rank0;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank2_rank0;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank2_real_int;
  f2py_numerical_utilities_def[i_f2py++].data = equal_rank1_real_int;
}
extern void F_FUNC_US(f2pyinitnumerical_utilities,F2PYINITNUMERICAL_UTILITIES)(void (*)(char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_numerical_utilities(void) {
  F_FUNC_US(f2pyinitnumerical_utilities,F2PYINITNUMERICAL_UTILITIES)(f2py_setup_numerical_utilities);
}


static FortranDataDef f2py_vector_matrix_utilities_def[] = {
  {"minkowski_conditions_check",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_vector_matrix_utilities_minkowski_conditions_check,doc_f2py_rout_num_types.f90_vector_matrix_utilities_minkowski_conditions_check},
  {"reduce_C_in_ABC",-1,{{-1}},0,NULL,(void *)f2py_rout_num_types.f90_vector_matrix_utilities_reduce_C_in_ABC,doc_f2py_rout_num_types.f90_vector_matrix_utilities_reduce_C_in_ABC},
  {NULL}
};

static void f2py_setup_vector_matrix_utilities(char *minkowski_conditions_check,char *reduce_C_in_ABC) {
  int i_f2py=0;
  f2py_vector_matrix_utilities_def[i_f2py++].data = minkowski_conditions_check;
  f2py_vector_matrix_utilities_def[i_f2py++].data = reduce_C_in_ABC;
}
extern void F_FUNC_US(f2pyinitvector_matrix_utilities,F2PYINITVECTOR_MATRIX_UTILITIES)(void (*)(char *,char *));
static void f2py_init_vector_matrix_utilities(void) {
  F_FUNC_US(f2pyinitvector_matrix_utilities,F2PYINITVECTOR_MATRIX_UTILITIES)(f2py_setup_vector_matrix_utilities);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "num_types.f90",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_num_types.f90(void) {
#else
#define RETVAL
PyMODINIT_FUNC initnum_types.f90(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = num_types.f90_module = PyModule_Create(&moduledef);
#else
  m = num_types.f90_module = Py_InitModule("num_types.f90", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module num_types.f90 (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'num_types.f90' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  numerical_utilities --- equal_rank1(),equal_rank2(),equal_rank3(),equal_scalar(),equal_scalar_real_int(),equal_scalar_int_int(),equal_rank1_rank0(),equal_rank2_rank0(),equal_rank2_real_int(),equal_rank1_real_int()""  vector_matrix_utilities --- minkowski_conditions_check(),reduce_C_in_ABC()"".");
  PyDict_SetItemString(d, "__doc__", s);
  num_types.f90_error = PyErr_NewException ("num_types.f90.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));












/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "vector_matrix_utilities", PyFortranObject_New(f2py_vector_matrix_utilities_def,f2py_init_vector_matrix_utilities));
  PyDict_SetItemString(d, "numerical_utilities", PyFortranObject_New(f2py_numerical_utilities_def,f2py_init_numerical_utilities));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"num_types.f90");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
