#!/bin/sh  
#  Loop to optimize
#######################  functions
get_temp()
{ awk -f awk_Tfinal fireballrun/fb
}

get_etot()
{ awk -f awk_etot fireballrun/fb
}

get_etrans()
{ awk -f awk_etrans fireballrun/Eparts.dat
}


######################## Initialize
n=0
nmax=1000
C="C"
H="H"
natoms=2
nparam1=2  #H parameters
nparam2=4  #C parameters
nparam=`expr $nparam1 + $nparam2  ` 
rm summary.dat
echo 'Run#' 'param1' 'param2' 'param3' 'param4'  'param5' 'param6' 'etot' 'Tfinal' 'Etrans' >summary.dat
echo 'Run#' 'param1' 'param2' 'param3' 'param4'  'param5' 'param6' 'etot' 'Tfinal' 'Etrans' 
echo 0.00 > energy.dat
#rm matout.dat
echo 2000 >matout.dat
rm *.eps
rm /output/*

## Make everything

cd ../progs
make
cd ../cprogs
make
cd ../begin_2007
make all


##### Initialize Begin
cd ../optimize2/beginrun
ifort -o optimizeinitial.x optimizeinitial.f90
ifort -o joinparam.x joinparam.f90
ifort -o splitparam.x splitparam.f90
cp ../input/begininput/*.* ../beginrun
rm begin.x
ln -s ../../begin_2007/begin.x begin.x

## Hydrogen
cp ../input/begininput/startparam1 parameters1 #for joinparam.x

## Carbon
# input parameters for V0 r0
cp ../input/begininput/startparam2 parameters2
./joinparam.x  #create parameters file from the two files

## create initialization
cd ../createrun
cp ../input/createinput/* ../createrun  #theory.input, create.input, etc (not folders)
rm create.x
ln -s ../../cprogs/create.x create.x
cd ..


############################## Loop #######################################################
while [ "$n" -lt "$nmax" ]
do
n=`expr $n + 1`
  echo "Run $n"
######  get parameters from Matlab

read matflag <matout.dat
while [ "$matflag" -gt 1000 ]
	
do
	read matflag <matout.dat
	echo 'waiting for matout.dat'
	sleep 1
	more energy.dat
	#more matout.dat  
done
#while [ ! -r matout.dat ]

#while [ ! -e matlab.dat ]
#do
#	echo 'waiting for matout.dat'
#	sleep 1
#	ls mat*  #without this, loop never sees the file matout.dat
#done
cp matout.dat  beginrun/parameters
echo 2000 >matout.dat

######## new initial.run.input files
cd beginrun

./splitparam.x
## Hydrogen
cp ../input/begininput/initial.run.inputHSN initial.run.input
cp parameters1 paramatom  #optimizeinitial uses paramatom
./optimizeinitial.x <initial.run.input >initialH.out  
./begin.x >beginoutH 
cp begin.input begin.input1
gnuplot statesH.plt
mv plot.eps "plot$H${n}.eps"
cp "plot$H${n}.eps" ../output
rm  "plot$H${n}.eps"

## Carbon
cp ../input/begininput/initial.run.inputsp initial.run.input
cp parameters2 paramatom  #optimizeinitial uses paramatom
./optimizeinitial.x <initial.run.input >initialC.out  #uses paramatom
./begin.x >beginoutC 
cp begin.input begin.input2
gnuplot statesSNsp.plt
mv plot.eps "plot$C${n}.eps"
cp "plot$C${n}.eps" ../output
rm "plot$C${n}.eps"
cp 0* ../createrun/cin/3opt/  #files with name starting with zero including wavefunctions
# get ready for create
cd ../createrun


  ###  
rm coutput/*
#./create.x > output.log    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


######## Fireball
cd ..

rm Fdata

# ln -s ../datafiles/CH3_C_5.1_6.2_H_5.3_CPrc-1.5/ Fdata
ln -s createrun/coutput/ Fdata 
cd fireballrun

cp ../input/fireballinput/* ../fireballrun
rm CHARGES
cp benzene.bas answer.bas
#./fireball.x >fb   #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#######  Extract items of interest
cd ..   #in optimize dir

Tf=`get_temp`
etot=`get_etot`
etrans=`get_etrans`
echo 'Writing energy.dat' $etot
echo $etot > energy.dat
sleep 2

######## Matlab
# Matlab reads parameters for initial guess.  It will then go to function and write matout.dat aand wait for energy.dat to be nonzero.

# script looks for energy.dat. If it equals zero it waits.  After it reads it, it sets the file to zero. 




# Write out parameters, results to summary file
{
	m=0
	while read param; do  #read returns exit code 1 when reading is OK
		m=`expr $m + 1`
		piece[$m]=$param
	#	echo $m $param
	done
} < beginrun/parameters

echo $n ${piece[1]} ${piece[2]} ${piece[3]} ${piece[4]} ${piece[5]} ${piece[6]} $etot $Tf $etrans >>summary.dat
echo $n ${piece[1]} ${piece[2]} ${piece[3]} ${piece[4]} ${piece[5]} ${piece[6]} $etot $Tf $etrans  







done  ######################### end of loop


